# Generated by Django 4.1.7 on 2023-03-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='NoPlays',
            new_name='no_plays',
        ),
    ]
