# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x0emotify.gateway\" \n\x12GetAccountsRequest\x12\n\n\x02id\x18\x01 \x03(\t\"@\n\x13GetAccountsResponse\x12)\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x17.motify.gateway.Account\"\x7f\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x61te_joined\x18\x04 \x01(\t\x12\x32\n\x0csubscription\x18\x05 \x01(\x0e\x32\x1c.motify.gateway.Subscription*A\n\x0cSubscription\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x42\x41SIC\x10\x01\x12\x0c\n\x08STANDARD\x10\x02\x12\x0b\n\x07PREMIUM\x10\x03\x32j\n\x0e\x41\x63\x63ountService\x12X\n\x0bGetAccounts\x12\".motify.gateway.GetAccountsRequest\x1a#.motify.gateway.GetAccountsResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBSCRIPTION._serialized_start=262
  _SUBSCRIPTION._serialized_end=327
  _GETACCOUNTSREQUEST._serialized_start=33
  _GETACCOUNTSREQUEST._serialized_end=65
  _GETACCOUNTSRESPONSE._serialized_start=67
  _GETACCOUNTSRESPONSE._serialized_end=131
  _ACCOUNT._serialized_start=133
  _ACCOUNT._serialized_end=260
  _ACCOUNTSERVICE._serialized_start=329
  _ACCOUNTSERVICE._serialized_end=435
# @@protoc_insertion_point(module_scope)
