trigger:
  branches:
    include:
      - main
  paths:
    include:
    - playlist
    - protos

resources:
- repo: self

pool: 
   vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'a4d10f07-2d31-481c-9fc0-77de7e0a6cd2'
  imageRepository: 'motifyplaylist'
  containerRegistry: 'motifybackend.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/playlist/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Test
  displayName: Run different types of test
  jobs:
  - job: Test
    displayName: Unit and Integration tests
    steps:
    - task: GoTool@0
      inputs:
        version: '1.20'
    - script: |
        pushd '$(Build.SourcesDirectory)/playlist' 
        go get -u github.com/jstemmer/go-junit-report 2>&1
        go get -u github.com/axw/gocov/gocov 2>&1
        go get -u github.com/AlekSi/gocov-xml 2>&1
        go test ./... -v -cover -coverprofile=coverage.txt 2>&1 | $HOME/go/bin/go-junit-report > report.xml
        $HOME/go/bin/gocov convert coverage.txt > coverage.json
        $HOME/go/bin/gocov-xml < coverage.json > coverage.xml
      displayName: Run unit tests & Generate coverage report
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '*report*.xml' 
        searchFolder: '$(Build.SourcesDirectory)/playlist'
      displayName: 'Publish test results'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/playlist/coverage.xml'
      displayName: 'Publish code coverage results'
- stage: Docker_Build
  displayName: Build and push docker image
  jobs:
  - job: Build
    displayName: Build docker image
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(Build.SourcesDirectory)'
        tags: '$(tag)'
- stage: Deployment
  displayName: Pull the name image in Container App
  jobs:
  - job: Deploy
    displayName: Pull the name image in Container App
    steps:
    - task: AzureContainerApps@0
      inputs:
        azureSubscription: 'Motify'
        acrName: 'motifybackend'
        imageToDeploy: '$(containerRegistry)/$(imageRepository):$(tag)'
        containerAppName: 'motify-dev-playlist'
        resourceGroup: 'motify-dev'
        containerAppEnvironment: 'motify-dev-managed-environment'
        targetPort: '60051'