# Generated by Django 4.1.7 on 2023-02-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscription',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='BASIC', max_length=8),
        ),
    ]
