# Generated by Django 4.1.7 on 2023-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_player', '0002_device_success_alter_device_name_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplayer',
            name='second',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='state',
            field=models.CharField(choices=[('PLAYING', 'Playing'), ('PAUSED', 'Paused')], default='PAUSED', max_length=10),
        ),
    ]
