# Generated by Django 4.1.7 on 2023-05-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_player', '0003_userplayer_second_userplayer_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'ip')},
        ),
    ]
