# Generated by Django 4.1.7 on 2023-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('user', models.CharField(blank=True, max_length=40, null=True)),
                ('NoPlays', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
